singleQuote: true
semi: true
printWidth: 100
useTabs: false
tabWidth: 2
vueIndentScriptAndStyle: true
quoteProps: 'as-needed'
bracketSpacing: true
trailingComma: 'es5'
jsxBracketSameLine: false
jsxSingleQuote: false
arrowParens: 'always'
insertPragma: false
requirePragma: false
proseWrap: 'never'
htmlWhitespaceSensitivity: 'strict'
endOfLine: 'auto'
rangeStart: 0
